export const auctionABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_auctionId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_bidder',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'AuctionBid',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_auctionId',
        type: 'uint256',
      },
    ],
    name: 'AuctionClosed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_creator',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_tokenAddress',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_tokenId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_currencyAddress',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_auctionId',
        type: 'uint256',
      },
    ],
    name: 'AuctionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_auctionId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_winner',
        type: 'address',
      },
    ],
    name: 'LotTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_auctionId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_creator',
        type: 'address',
      },
    ],
    name: 'RepaymentTransferred',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_auctionId', type: 'uint256' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'bid',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'buyNow',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'claimLot',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'claimRepayment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'closeAuction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'countOfAuctions',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_tokenAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      { internalType: 'uint256', name: '_startPrice', type: 'uint256' },
      { internalType: 'uint256', name: '_buyNowPrice', type: 'uint256' },
      { internalType: 'uint256', name: '_startTime', type: 'uint256' },
      { internalType: 'uint256', name: '_duration', type: 'uint256' },
      { internalType: 'uint256', name: '_durationIncrement', type: 'uint256' },
      { internalType: 'uint256', name: '_bidIncrement', type: 'uint256' },
      { internalType: 'string', name: '_description', type: 'string' },
    ],
    name: 'createAuction',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'getAuctionInfo',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'uint256', name: 'startPrice', type: 'uint256' },
          { internalType: 'uint256', name: 'buyNowPrice', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'duration', type: 'uint256' },
          {
            internalType: 'uint256',
            name: 'durationIncrement',
            type: 'uint256',
          },
          { internalType: 'uint256', name: 'bidIncrement', type: 'uint256' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'address', name: 'tokenAddress', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'address', name: 'currencyAddress', type: 'address' },
          { internalType: 'address', name: 'currentBidder', type: 'address' },
          { internalType: 'uint256', name: 'highestBid', type: 'uint256' },
          { internalType: 'bool', name: 'lotBought', type: 'bool' },
          { internalType: 'bool', name: 'repaymentTransferred', type: 'bool' },
          { internalType: 'bool', name: 'lotTransferred', type: 'bool' },
        ],
        internalType: 'struct Auction.AuctionInfo',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'getRaisingBid',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_auctionId', type: 'uint256' }],
    name: 'getStatus',
    outputs: [
      { internalType: 'enum Auction.AuctionStatus', name: '', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
